# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "dev"
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "dev"
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/jstrachan/jx-demo-gke2-dev.git
  kind: Development
  label: Development
  namespace: jx
  promotionStrategy: "Never"
  webHookEngine: "Lighthouse"
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    buildPackRef: "master"
    buildPackUrl: "https://github.com/jenkins-x/jxr-packs-kubernetes.git"
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: jx-meta-pipeline
    dockerRegistryOrg: ""
    envOrganisation: jstrachan
    gitServer: https://github.com
    helmTemplate: true
    kubeProvider: "gke"
    pipelineUsername: "jstrachan"
    pipelineUserEmail: "jenkins-x@googlegroups.com"
    prowConfig: Scheduler
    importMode: YAML
    promotionEngine: Prow
    prowEngine: Tekton
    versionStreamUrl: "https://github.com/jenkins-x/jenkins-x-versions.git"
    versionStreamRef: "master"
    useGitOps: true
    storageLocations:
      - bucketUrl: gs://logs-jstrachan-tekton3-d3ca9654053a
        classifier: logs
      - bucketUrl: gs://reports-jstrachan-tekton3-d3ca9654053a
        classifier: reports
