# Source: nodey534/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nodey534
  namespace: jx-staging
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: nodey534
              servicePort: 80
      host: nodey534-jx-staging.34.105.246.143.nip.io
