apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        jstrachan/jx-demo-gke2-dev: true
        jstrachan/nodey536: true
        jstrachan/nodey545: true
        jstrachan/nodey546: true
        jstrachan/nodey553: true
        jstrachan/nodey554: true
        jstrachan/nodey560: true
        jstrachan/rust-demo3: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jstrachan/jx-demo-gke2-dev: merge
        jstrachan/nodey536: merge
        jstrachan/nodey545: merge
        jstrachan/nodey546: merge
        jstrachan/nodey553: merge
        jstrachan/nodey554: merge
        jstrachan/nodey560: merge
        jstrachan/rust-demo3: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx-demo-gke2-dev
        - jstrachan/nodey536
        - jstrachan/nodey545
        - jstrachan/nodey546
        - jstrachan/nodey553
        - jstrachan/nodey554
        - jstrachan/nodey560
        - jstrachan/rust-demo3
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx-demo-gke2-dev
        - jstrachan/nodey536
        - jstrachan/nodey545
        - jstrachan/nodey546
        - jstrachan/nodey553
        - jstrachan/nodey554
        - jstrachan/nodey560
        - jstrachan/rust-demo3
      target_url: http://dashboard-jx.34.89.8.12.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
