# Source: jenkins-resources/templates/maven-settings-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
  namespace: myjenkinsa
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: settings.xml
      key: jstrachan-tekton3-jx-maven-settings
      property: settingsXml
      version: latest
    - name: settings-security.xml
      key: jstrachan-tekton3-jx-maven-settings
      property: securityXml
      version: latest
  template:
    type: Opaque
