apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: jstrachan
    provider: https://github.com
    providerKind: github
    repositories:
    - name: nodey536
    - name: nodey545
    - name: nodey534
    scheduler: in-repo
